# Based on https://github.com/flycheck/emacs-travis

language: emacs-lisp
sudo: false

cache:
  apt: true
  timeout: 691200
  directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
      - "$HOME/.emacs.d/"

# Allow Emacs snapshot builds to fail and don't wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

git:
  depth: 1

env:
  matrix:
    - EMACS_VERSION=24.3
    - EMACS_VERSION=24.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=snapshot

before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Configure $EMACS_MAJOR_VERSION: The 'checkdoc-file' exist on Emacs >= 25.1
  - export EMACS_MAJOR_VERSION="$(echo $EMACS_VERSION | cut -d '.' -f 1)"
  # Download the makefile to emacs-travis.mk
  - wget --quiet 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -s -f emacs-travis.mk install_emacs
  - make -s -f emacs-travis.mk install_cask
  # Install Texinfo
  - make -s -f emacs-travis.mk install_texinfo

install:
  # Install dependencies
  - cask install

script:
  # Make sure the exact emacs version can be found in the build output
  - emacs -Q --batch --eval '(message (emacs-version))'
  - '[[ "$EMACS_MAJOR_VERSION" = "24" ]] || make checkdoc'
  - make test

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
