language: emacs-lisp
sudo: required

env:
  matrix:
    - EMACS_VERSION=emacs-24.3-bin
    - EMACS_VERSION=emacs-24.4-bin
    - EMACS_VERSION=emacs-24.5-bin
    - EMACS_VERSION=emacs-25.1-bin
    - EMACS_VERSION=emacs-snapshot

before_install:
  # Use the ubuntu emacs teams regularly updated snapshot packages
  - '[[ "$EMACS_VERSION" != "emacs-snapshot" ]] || sudo add-apt-repository -y ppa:ubuntu-elisp/ppa'
  - '[[ "$EMACS_VERSION" != "emacs-snapshot" ]] || sudo apt-get update -qq'
  - '[[ "$EMACS_VERSION" != "emacs-snapshot" ]] || sudo apt-get install -qq $EMACS_VERSION'
  - '[[ "$EMACS_VERSION" != "emacs-snapshot" ]] || sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-nox'

  # Use emacs version manager for all other versions
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install $EMACS_VERSION --use || true

script:
  # Make sure the exact emacs version can be found in the build output
  - emacs -Q --batch --eval '(message (emacs-version))'
  # - make test
